### ISSUE TITLE
platform_device_id-1.0.1 depends on discontinued package: device_info

### ISSUE THREAD

**Issue by 4bSolutionsLLP** [BestBurning/platform_device_id#26]
platform_device_id-1.0.1 depends on device_info, which has been discontinued - see: https://pub.dev/packages/device_info
and is replaced by device_info_plus: https://pub.dev/packages/device_info_plus

**Comment by ollydixon** [comment]
Too add to this, ``device_info`` no longer compiles for production projects also; this needs to be updated fairly urgently.

**Comment by ollyde** [comment]
For anyone else who needs to update. This will fix the build error ```fatal error: module 'device_info' not found``` for production releases.

For now you can use this inside the pubspec.yaml

```
platform_device_id:
    git:
      url: https://github.com/ollydixon/platform_device_id
      ref: master
      path: platform_device_id/
```

I've also created a pull request to fix it; 
https://github.com/BestBurning/platform_device_id/pull/28

Let's hope the author sees it.
