### ISSUE TITLE
Please adapt for Flutter3.10.5，Gradle8.0.1，Kotlin 1.5.20

### ISSUE THREAD

**Issue by DennisJu007** [BestBurning/platform_device_id#40]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':platform_device_id' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by helderlj** [comment]
Please update this

**Comment by sveinbjornt** [comment]
I am having the same problem. An updated version would be very much appreciated.

**Comment by dvdstrk** [comment]
Same.  Is there a workaround for this?

**Comment by tommysolsen** [comment]
Yes, there is.

Fork this library, and apply the changes from PR #42 to your fork, it fixes your issue. Then update your pubspec.yml to point to your git repo instead.

```
  platform_device_id:
    git:
      url: git@github.com:tommysolsen/platform_device_id.git
      path: platform_device_id
```

The repo contains several packages, so you must set path as well
